name: NEAR NFT Checker

on:
  # We want to trigger the build & test pipelines in every branch.
  push:
    # But do no run the pipeline when only `md` files are modified.
    paths-ignore:
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    env:
      TESTNET_MASTER_ACCOUNT: nft-contracts-checker.testnet
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
    - uses: actions/download-artifact@v2

    - run: yarn install --frozen-lockfile
    - run: TESTNET_SEED_PHRASE=secrets.TESTNET_SEED_PHRASE yarn build:web
    - run: git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
    - run: yarn gh-pages-clean
    - run: yarn deploy:web --user "Github Workflow Bot <noemail@epam.github.io>"
